name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag postfix-milters:test
    - name: Test container runtime
      run: |
        echo "Starting container for 10 second runtime test..."
        docker run -d --name milters-test postfix-milters:test
        
        echo "Waiting 10 seconds..."
        sleep 10
        
        echo "Checking container status..."
        if ! docker ps --filter "name=milters-test" --format "table {{.Names}}\t{{.Status}}" | grep -q "Up"; then
          echo "ERROR: Container is not running after 10 seconds"
          docker logs milters-test
          docker rm -f milters-test || true
          exit 1
        fi
        
        echo "Getting container logs..."
        docker logs milters-test
        
        echo "Checking for error patterns in logs..."
        if docker logs milters-test 2>&1 | grep -iE "(error|failed|exception|fatal)"; then
          echo "ERROR: Found error patterns in container logs"
          docker rm -f milters-test || true
          exit 1
        fi
        
        echo "Stopping and removing test container..."
        docker stop milters-test
        docker rm milters-test
        
        echo "Container runtime test passed!"
